### ISSUE TITLE
Issues in 4.1.0

### ISSUE THREAD

**Issue by rgeneaux** [PyMoDAQ/pymodaq_plugin_manager#16]
Hi, a few bug reports of the plugin manager in pymdoaq == 4.1.0b0

- parsing error of plugin_manager version, fixed by https://github.com/PyMoDAQ/pymodaq_plugin_manager/pull/15

- the "Check updates" button always returns "there is a newer version available !"
indeed when reading the current plugin_manager version, we execute 
`from pymodaq_plugin_manager import __version__ as version`
which ends reading the value in `'data/PluginList.json'`
for me, this value is 0.0.17 regardless of the actual manager version, so the manager always thinks there is a newer version

- The list of available plugins is always empty in 4.1.0b0! 
This is because on line 158 of validate.py, `pymodaq_version in specifier` returns `False` for `pymodaq_version =Version('4.1.0b0')` and `specifier = '>=4.0' `. But it works with `pymodaq_version =Version('4.1.0')` ("b0" is the issue).

**Comment by seb5g** [comment]
I'm looking at it now
