### ISSUE TITLE
plugin_manager

### ISSUE THREAD

**Issue by quantumm** [PyMoDAQ/pymodaq_plugin_manager#2]
It sounds like the plugin manager is not working anymore :/
It cannot find any of them.

**Comment by seb5g** [comment]
This seems to answer your issue:
https://stackoverflow.com/questions/51950533/fatal-python-error-init-sys-streams-cant-initialize-sys-standard-streams-attr/56283693

basically remove from your ``Path`` env variable (both user and system) any path pointing to a given python distrib and try again

**Comment by quantumm** [comment]
Here are my PATH variables:

![Capture](https://user-images.githubusercontent.com/5221986/113003649-37e5b680-9173-11eb-9e87-d41e79a64eb7.PNG)

i do not see a reference to a python distribution.
I tried again with a fresh installation but the problem is still the same :/

**Comment by quantumm** [comment]
But in the command line i got this:

`(tmp_pymodaq_plugin_manager) C:\Users\dbrestea>echo %PATH%                                                              C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_plugin_manager;C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_plugin_manager\Library\mingw-w64\bin;C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_plugin_manager\Library\usr\bin;C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_plugin_manager\Library\bin;C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_plugin_manager\Scripts;C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_plugin_manager\bin;C:\Users\dbrestea\Anaconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\PuTTY;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\IVI Foundation\VISA\Win64\Bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Users\dbrestea\AppData\Local\Microsoft\WindowsApps;C:\Users\dbrestea\AppData\Local\Programs\Git\cmd`

Maybe because it is not the same user ?…
