### ISSUE TITLE
Installation waits for user input

### ISSUE THREAD

**Issue by Semptum** [PyMoDAQ/pymodaq_plugin_manager#20]
Hi,
I made a comment on the corresponding commit but I'm not sure how comments work here so I thought I'd make a proper issue.

When I try to install a plugin, the plugin manager opens a Python shell in the terminal from which I opened the plugin manager. That shell allows input like a normal python shell and is blocking the execution. Closing the shell using Ctrl+D results in the plugin manager showing the *successful installation* dialog without actually completing the installation. Specifically it seems to be waiting on `sp.stdout.readline()`.

I traced the issue to a 3-year old commit, where you changed the `do_subprocess()` function in the file `manager.py`. In the creation of the sub-process, you set the `shell` flag to `True`. Disabling it results in what I assume is the intended behavior: the output of `pip` is streamed to the main window and the package installation is successfully completed.
I'm not sure why the `shell=True` is present, a cursory glance at the Python documentation doesn't seem to indicate that it's necessary here. But I've never had to work with sub-processes so I'm not sure.

I'm running Python 3.11.7 and PyMoDaq 4.1.1
I'm on Arch (btw)

I can run some tests if necessary.
Thanks in advance,
Semptum

**Comment by seb5g** [comment]
do you want to do a PR to modify this, I'll then try it on my machine?

**Comment by Semptum** [comment]
Sure thing, thanks

**Comment by seb5g** [comment]
your PR has been merged and solves this issue. I'm closing it
