### ISSUE TITLE
plugin manager - after 'yes to install' program freezes

### ISSUE THREAD

**Issue by AnjaTRPES** [PyMoDAQ/pymodaq_plugin_manager#7]
In an effort to update our existing software from a hash-mash of labview/python, I freshly installed pymodaq in a seperate virtual environment on my Debian machine. After getting rid of an error (see https://github.com/tasmota/tasmotizer/issues/71)) related to pyqt5, I was very happy that I could finally launch the guis. 
The pre-installed plugins (=the mock detectors etc) seem to work just fine, so I went on ahead to install some needed plugins using dashboard/plugin manager.
This results in an error:
`qt.tpa.scb QXcbConnection: XCB error: 3(BadWindow), sequence: 1601, resource id: 25175710, major code: 40 (TranslateCoords), minor code: 0`
I suspect it might have something to do with the error I had with pyqt5 earlier, though a google search did not yield any satisfactory results(=finding the same error code).

Do you have any ideas what the cause of this could be? Is there an alternative to install plugins?

**Comment by AnjaTRPES** [comment]
I tried now with the harvesters-gui to access cameras - and encountered the same error. It seems to be an issue with the debian installation - and I don't see an easy way to fix it.

**Comment by seb5g** [comment]
I'm not sure it will help but it somehow looks like an issue we've faced with my student while automating testing on a remote linux server. We had to add these lines for Qt to work properly:

`sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0`

Would you try and let me know?

**Comment by seb5g** [comment]
it does the job
